source 'https://rubygems.org'
ruby '2.2.3'

gem 'rails', '~> 4.2.5.1'
gem 'jbuilder', '~> 2.4.1'
gem 'devise', '~> 3.4.1'
gem 'bcrypt', '~> 3.1.10'
gem 'zurb-ink-rails', '~> 1.0.5'
gem 'sass-rails', '~> 5.0.3'
gem 'uglifier', '~> 2.7.2'
gem 'font-awesome-rails', '~> 4.5.0.1'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'haml', '~> 4.0.7'
gem 'redactor-rails', '0.5.0'
gem 'angular-rails-templates', '~> 1.0.0'
gem 'selectize-rails', '0.12.1'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.37'
gem 'wkhtmltopdf-binary', '0.9.9.3'
gem 'pdfkit', '~> 0.8.2'
gem 'puma'
gem 'pg'
gem 'jquery-rails'
gem 'yajl-ruby'
gem 'devise_masquerade'
gem 'activerecord-session_store'
gem 'sidekiq'
gem 'rails_admin'
gem 'authority'
gem 'fog'
gem 'mini_magick'
gem 'carrierwave'
gem 'twitter'
gem 'mandrill-api'
gem 'mandrill_mailer'
gem 'descriptive-statistics'
gem 'premailer-rails'
gem 'actionpack-action_caching'
gem 'aws-s3'

source 'https://rails-assets.org' do
  gem 'rails-assets-moment', '2.10.3'
  gem 'rails-assets-jquery', '2.1.4'
  gem 'rails-assets-underscore', '1.8.3'
  gem 'rails-assets-highcharts', '= 3.0.10'
  gem 'rails-assets-angular', '~> 1.2.0'
  gem 'rails-assets-angular-route', '1.2.28'
  gem 'rails-assets-angular-sanitize', '1.2.28'
  gem 'rails-assets-angular-resource', '1.2.28'
  gem 'rails-assets-angular-ui-router', '0.2.15'
  gem 'rails-assets-momentjs', '2.10.3'
  gem 'rails-assets-angular-redactor', '1.1.4'
  gem 'rails-assets-angular-bootstrap', '0.12.1'
  gem 'rails-assets-angular-moment', '0.10.1'
  gem 'rails-assets-angular-ui-utils', '0.2.3'
  gem 'rails-assets-angular-file-upload', '~> 1.1.5'
  gem 'rails-assets-rollbar', '1.2.2'
  gem 'rails-assets-angular-shims-placeholder', '0.4.2'
end

group :development, :test do
  gem 'foreman'
  gem 'dotenv-rails'
  gem 'spring-commands-rspec'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'annotate'
  gem 'letter_opener'
  gem 'letter_opener_web'
  gem 'jasmine', '2.3.0'
  gem 'rails-assets-angular-mocks', '1.2.28'
  gem 'pry', '0.10.1'
  gem 'rake', '10.5.0'
end

group :test do
  gem 'rspec', '~> 3.4.0'
  gem 'rspec-rails', '~> 3.4.2'
  gem 'rspec-collection_matchers'
  gem 'shoulda-matchers', '~> 3.1.1'
  gem 'faker', '~> 1.6.1'
  gem 'rspec-sidekiq', '~> 2.2.0'
  gem 'factory_girl_rails', '~> 4.6.0'
  gem 'database_cleaner', '~>1.5.1'
end

group :production do
  gem 'memcachier'
  gem 'dalli'
  gem 'rails_12factor'
end
