development:
  s3_access_key: <%= ENV['S3_KEY'] %>
  s3_secret_key: <%= ENV['S3_SECRET'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
production:
  s3_access_key: <%= ENV['S3_KEY'] %>
  s3_secret_key: <%= ENV['S3_SECRET'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>