development:
  s3_access_key: <%= ENV['s3_access_key'] %>
  s3_secret_key: <%= ENV['s3_secret_key'] %>
  s3_bucket: <%= ENV['s3_bucket'] %>
production:
  s3_access_key: <%= ENV['s3_access_key'] %>
  s3_secret_key: <%= ENV['s3_secret_key'] %>
  s3_bucket: <%= ENV['s3_bucket'] %>