development:
  s3_access_key: <%= ENV['S3_KEY'] %>
  s3_secret_key: <%= ENV['S3_SECRET'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>
production:
  s3_access_key: <%= ENV['S3_KEY'] %>
  s3_secret_key: <%= ENV['S3_SECRET'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>